### PR TITLE
add ability to delete merchant pricing trend downloads

### PR DESCRIPTION
**Pull request by pashgo**

### CODE REVIEW

**Comment by shavkat-samatov** [comment]
👍

**Comment by shavkat-samatov** [comment]
@pashgo probably out of scope of that pull probably, but wanted to tell that I noticed that in `delete_download` we are passing owner_id, download_ids and also extra options and I'm not sure extra options are used on gAPI side , now in `delete_merchant_pricing_trend_download` we also pass owner_id, external_record_id and options and I'm not sure if these options are used on gAPI side as well

**Comment by pashgo** [comment]
@shavkat-samatov This options is used to make Faraday request. You can pass headers, proxy etc 

https://github.com/GapIntelligence/gapintelligence-gem/blob/master/lib/gap_intelligence/client/requestable.rb#L14

**Comment by shavkat-samatov** [comment]
@pashgo 👍

**Pull request merged**
